### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by Maikuolan** [Maikuolan/GitHub-OS-POEditor-Projects-List#2]
Putting this repository up for adoption, if anyone else wants to take it over. (I don't use POEditor myself anymore since the past few years, and I don't foresee myself doing any more work at this repository).

**Comment by Maikuolan** [comment]
Tagging some possibly interested users I can think of (via stars, forks, etc), before I post about this anywhere else: @petk @hworld @DandelionSprout

**Comment by DandelionSprout** [comment]
Unfortunately I don't think POEditor is a particularly popular tool, especially for the narrow subset of GitHub-hosted open-source projects. Of the ≥60 translation projects I've worked on in the past 3 years, only 1 used POEditor. Crowdİn and Transifex have become *far* more popular among project owners over the years.

Give me a couple of days to think about whether it's worth it for me to take over it, in whichever kind of way the handover would be done.

**Comment by DandelionSprout** [comment]
Okay, so since maintaining a repo like this would require virtually zero effort from me, I've chose to accept your offer.

How do you want to do the transfer?

**Comment by Maikuolan** [comment]
The repo isn't tied into any external apps, integrations, etc, and the current applied license schema is the "Unlicense" license, so, there shouldn't be any complications in that regard. I'm thinking a direct ownership transfer would be the easiest way to go. Once I transfer it, it becomes yours, and at that point, it'll be up to you what happens with it thereafter. Sound good? :-)

**Comment by DandelionSprout** [comment]
Sounds good enough for me.

**Comment by Maikuolan** [comment]
Excellent. :-)

I tried transferring it just now, but GitHub didn't let me transfer it due to the existence of the fork; we might need to sort out the fork first. I'll try transferring it again once that's been sorted out.

![Untitled](https://user-images.githubusercontent.com/12571108/62997745-d092ca00-be9b-11e9-8a86-6cce34834c6e.png)

**Comment by DandelionSprout** [comment]
Okay, so now I've finally got around to deleting that old repo of mine, so now you can try to transfer again, I suppose.

**Comment by Maikuolan** [comment]
Done. :+1: :-)

**Comment by Maikuolan** [comment]
Closing the issue now due to that the repository has now been successfully adopted (in case others decide to reply at a later date otherwise). Thank you to @DandelionSprout. :-)
